version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: lms_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-lms}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - lms-network

  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: lms_api
    restart: always
    environment:
      DATABASE_URL: postgresql://${DB_USER:-postgres}:${DB_PASSWORD:-postgres}@db:5432/${DB_NAME:-lms}?schema=public
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET:-supersecret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-supersecretrefresh}
      PORT: 3002
      NPM_CONFIG_UPDATE_NOTIFIER: 'false'
      NPM_CONFIG_FUND: 'false'
      PRISMA_TELEMETRY_DISABLE: 'true'
      DO_NOT_TRACK: '1'
    command: >
      sh -c "npx prisma db push --schema=packages/database/prisma/schema.prisma --accept-data-loss && node apps/api/dist/main"
    ports:
      - "3002:3002"
    depends_on:
      - db
    networks:
      - lms-network

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://localhost:3002
    container_name: lms_web
    restart: always
    environment:
      NODE_OPTIONS: '--dns-result-order=ipv4first'
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3002
      API_URL: http://api:3002
      PORT: 3000
    ports:
      - "3003:3000"
    depends_on:
      - api
    networks:
      - lms-network
    extra_hosts:
      - "localhost:host-gateway"

volumes:
  pgdata:


networks:
  lms-network:
    driver: bridge
