[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]

[phases.install]
cmds = [
  "npm ci --include=dev --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npx prisma generate --schema=./packages/database/prisma/schema.prisma",
  "npx prisma db push --schema=./packages/database/prisma/schema.prisma --accept-data-loss --skip-generate",
  "cd packages/database && npm run build",
  "cd packages/email && npm run build",
  "cd apps/api && npm run build"
]

[start]
cmd = "cd apps/api && node dist/main"

[variables]
NODE_ENV = "production"
