[phases.setup]
nixPkgs = ["nodejs-20_x", "openssl"]

[phases.install]
cmds = [
  "cd packages/database && npm install",
  "cd packages/email && npm install", 
  "cd packages/config && npm install",
  "npm install --legacy-peer-deps"
]

[phases.build]
cmds = [
  "npx prisma generate --schema=./packages/database/prisma/schema.prisma",
  "cd apps/api && npm run build"
]

[start]
cmd = "cd apps/api && node dist/main"

[variables]
NODE_ENV = "production"
